plugins {
    id 'com.android.application'
}

android {
    namespace 'com.learnershift.splitsnap'
    compileSdk 35

    defaultConfig {
        applicationId 'com.learnershift.splitsnap'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    sourceSets {
        main.assets.srcDirs('../../dist')
    }
}
